<a href="https://colab.research.google.com/github/25wh1a05ch-RP/NASSCOM/blob/main/WEEK2/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1 Create a 1D array with numbers from 0 to 99
arr1_1 = np.arange(100)

# 1.2 Create a 3x3 array filled with ones
arr1_2 = np.ones((3, 3))

# 1.3 Create a 2x4 array filled with 7
arr1_3 = np.full((2, 4), 7)

# 1.4 Create a 5x5 array with random integers from 10 to 50
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


# Task 2: Indexing and Slicing with Arrays
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# 2.1 Extract element at row 2, column 3
val2_1 = data[2, 3]

# 2.2 Extract the first row
row2_2 = data[0]

# 2.3 Extract the last column
col2_3 = data[:, -1]

# 2.4 Extract rows 1 and 2, columns 0 and 1
sub_arr2_4 = data[1:3, 0:2]

# 2.5 Select all elements greater than 100
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


# Task 3: Conditional Operations
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(
    1, 21, size=(4, 5)
)

# 3.1 Replace values less than 10 with 0
arr3_2 = np.where(
    arr3_1 < 10,
    0,
    arr3_1
)

# 3.2 Count the number of even elements
even_count3_3 = np.sum(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("Number of even elements:", even_count3_3)


# Task 4: Aggregation Functions
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([
    [10, 5, 12],
    [3, 8, 15],
    [20, 7, 4]
])

# 4.1 Sum of all elements
sum4_1 = np.sum(arr4_1)

# 4.2 Mean of each column
mean_cols4_2 = np.mean(
    arr4_1,
    axis=0
)

# 4.3 Maximum value in each row
max_rows4_3 = np.max(
    arr4_1,
    axis=1
)

# 4.4 Standard deviation of the entire array
std4_4 = np.std(arr4_1)

print("Sum:", sum4_1)
print("Column means:", mean_cols4_2)
print("Row maximums:", max_rows4_3)
print("Standard deviation:", std4_4)


# Task 5: Reshaping and Flattening
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

# 5.1 Reshape into a 4x6 array
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2 Reshape into a 2x3x4 array
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

# 5.3 Flatten using both ravel() and flatten()
flattened_arr5_4 = reshaped_arr5_2.ravel()
flattened_arr5_4_copy = reshaped_arr5_2.flatten()

print("4x6 array:\n", reshaped_arr5_2)
print("2x3x4 array:\n", reshaped_arr5_3)
print("Flattened using ravel():", flattened_arr5_4)
print("Flattened using flatten():", flattened_arr5_4_copy)


# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add the vector to each row
result6_2 = arr6_1 + vector

print("result6_1:\n", result6_1)
print("result6_2:\n", result6_2)


# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view and modify it
view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("Original after modifying view:")
print(original_arr7)

# 7.2 Create a copy and modify it
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original after modifying copy:")
print(original_arr7)

print("Modified copy:")
print(copy_arr7)


# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([
    [1, 2],
    [3, 4]
])

arr8_b = np.array([
    [5, 6],
    [7, 8]
])

arr8_c = np.array([
    [9, 10]
])

# 8.1 Vertically stack arr8_a and arr8_b
vstack_arr8_1 = np.vstack(
    (arr8_a, arr8_b)
)

# 8.2 Horizontally stack arr8_a and arr8_b
hstack_arr8_2 = np.hstack(
    (arr8_a, arr8_b)
)

# 8.3 Add arr8_c below the vertically stacked array
combined_arr8_3 = np.vstack(
    (vstack_arr8_1, arr8_c)
)

# 8.4 Split into 3 equal row parts
part1, part2, part3 = np.array_split(
    combined_arr8_3,
    3
)

print("Vertical stack:\n", vstack_arr8_1)
print("Horizontal stack:\n", hstack_arr8_2)
print("Combined array:\n", combined_arr8_3)
print("Part 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)


# Task 9: Sorting and Searching
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([
    5, 2, 8, 1, 9, 4, 7, 3, 6
])

arr9_2d = np.array([
    [30, 20, 10],
    [60, 50, 40],
    [90, 80, 70]
])

# 9.1 Sort the 1D array
sorted_arr9_1 = np.sort(arr9_1)

# 9.2 Sort each column independently
sorted_cols9_2 = np.sort(
    arr9_2d,
    axis=0
)

# 9.3 Find the index where the value is 9
idx9_3 = np.where(arr9_1 == 9)

# 9.4 Find the index of the maximum value
max_idx9_4 = np.argmax(arr9_1)

print("Sorted 1D array:", sorted_arr9_1)
print("Columns sorted independently:\n", sorted_cols9_2)
print("Index where value is 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)

--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[49 41 43 37 40]
 [17 48 35 43 12]]

--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]

--- Task 3: Conditional Operations ---
arr3_1:
 [[ 2  6 18  2 18]
 [15 19  2 20  6]
 [ 1 15 10 19 17]
 [ 5  4 10 17 10]]
arr3_2:
 [[ 0  0 18  0 18]
 [15 19  0 20  0]
 [ 0 15 10 19 17]
 [ 0  0 10 17 10]]
Number of even elements: 12

--- Task 4: Aggregation Functions ---
Sum: 84
Column means: [11.          6.66666667 10.33333333]
Row maximums: [12 15 20]
Standard deviation: 5.2493385826745405

--- Task 5: Reshaping and Flattening ---
4x6 array: