<a href="https://colab.research.google.com/github/25wh1a05ch-RP/NASSCOM/blob/main/WEEK2/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:

import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert the NumPy array into a Pandas DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=["A", "B", "C", "D"]
)

print("Series s1_1:")
print(s1_1)

print("\nNumPy array np_array1_2:")
print(np_array1_2)

print("\nDataFrame df1_3:")
print(df1_3)


# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Create a date range with 100 dates
dates = pd.date_range(
    start="2023-01-01",
    end="2023-04-10",
    periods=100
)

# Create the DataFrame
df_sales = pd.DataFrame({
    "Date": dates,
    "Region": np.random.choice(
        ["East", "West", "North", "South"],
        size=100
    ),
    "Product": np.random.choice(
        ["Laptop", "Mouse", "Keyboard", "Monitor"],
        size=100
    ),
    "Sales": np.random.randint(100, 1001, size=100),
    "Quantity": np.random.randint(1, 11, size=100)
})

# Introduce 5 random NaN values in the Sales column
sales_nan_indices = np.random.choice(
    df_sales.index,
    size=5,
    replace=False
)
df_sales.loc[sales_nan_indices, "Sales"] = np.nan

# Introduce 3 random NaN values in the Quantity column
quantity_nan_indices = np.random.choice(
    df_sales.index,
    size=3,
    replace=False
)
df_sales.loc[quantity_nan_indices, "Quantity"] = np.nan

print("\nFirst 5 rows of df_sales:")
print(df_sales.head())


# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[["Region", "Sales"]]

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales["Product"] == "Laptop"]

# 3.3 Select rows where Region is East and Sales is greater than 500
df3_3 = df_sales[
    (df_sales["Region"] == "East") &
    (df_sales["Sales"] > 500)
]

# 3.4 Select the Sales value for the first entry where Product is Monitor
val3_4 = df_sales.loc[
    df_sales["Product"] == "Monitor",
    "Sales"
].iloc[0]

print("\ndf3_1:")
print(df3_1.head())

print("\ndf3_2:")
print(df3_2.head())

print("\ndf3_3:")
print(df3_3.head())

print("\nFirst Sales value where Product is Monitor:")
print(val3_4)


# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Count missing values in each column
missing_counts4_1 = df_sales.isnull().sum()

# 4.2 Fill missing Sales values with the mean Sales value
df4_2_filled = df_sales.copy()

df4_2_filled["Sales"] = (
    df4_2_filled["Sales"]
    .fillna(df4_2_filled["Sales"].mean())
)

# 4.3 Drop rows containing any missing values
df4_3_dropped = df_sales.dropna()

print("\nMissing values in each column:")
print(missing_counts4_1)

print("\nDataFrame after filling missing Sales values:")
print(df4_2_filled.head())

print("\nDataFrame after dropping rows with missing values:")
print(df4_3_dropped.head())


# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue column
df_sales["Total_Revenue"] = (
    df_sales["Sales"] * df_sales["Quantity"]
)

# 5.2 Sort by Date ascending and Sales descending
df5_2_sorted = df_sales.sort_values(
    by=["Date", "Sales"],
    ascending=[True, False]
)

# 5.3 Group by Region and calculate the sum of Sales and Quantity
df5_3_grouped_region = (
    df_sales
    .groupby("Region")[["Sales", "Quantity"]]
    .sum()
)

# 5.4 Group by Product and calculate the average Sales
df5_4_grouped_product = (
    df_sales
    .groupby("Product")["Sales"]
    .mean()
)

print("\ndf_sales with Total_Revenue:")
print(df_sales.head())

print("\nSorted DataFrame:")
print(df5_2_sorted.head())

print("\nSum of Sales and Quantity by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)



--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy array np_array1_2:
[[ 52  93  15  72]
 [ 61  21  83  87]
 [ 75  75  88 100]]

DataFrame df1_3:
    A   B   C    D
0  52  93  15   72
1  61  21  83   87
2  75  75  88  100

--- Task 2: Synthetic Data Generation for Practice ---

First 5 rows of df_sales:
        Date Region  Product  Sales  Quantity
0 2023-01-01  South    Mouse  624.0       1.0
1 2023-01-02  South  Monitor  259.0       9.0
2 2023-01-03  North   Laptop  938.0       6.0
3 2023-01-04   West  Monitor  798.0       3.0
4 2023-01-05   East   Laptop  342.0       4.0

--- Task 3: Indexing and Slicing in DataFrames ---

df3_1:
  Region  Sales
0  South  624.0
1  South  259.0
2  North  938.0
3   West  798.0
4   East  342.0

df3_2:
         Date Region Produ